# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


before_install:
- sudo rm -vf /etc/apt/sources.list.d/*riak*
- sudo apt-get update
language: R
sudo: false
cache:
 - packages
 - apt
warnings_are_errors: false
